apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
  